import Link from "next/link";
import { PRODUCT } from "@/lib/catalog";

const facts = [
  ["01", "A clear formulation", "Karela, Jamun and 15+ Ayurvedic herbs, presented with responsible product information."],
  ["02", "Made for a routine", "A simple format for customers who want to build a thoughtful everyday wellness habit."],
  ["03", "Straightforward buying", "One product, clear pricing, secure checkout architecture and customer order visibility."]
];

export default function Home() {
  return <main className="site-shell">
    <header className="site-header"><div className="header-inner"><Link className="wordmark" href="/">ValuVeda Wellness</Link><nav className="nav-links" aria-label="Primary"><Link href="#story">Our approach</Link><Link href="#details">Product details</Link><Link href="#faq">FAQ</Link></nav><div className="header-actions"><Link className="pill-outline" href="/account/login">Account</Link><Link className="pill" href="/product">Shop now</Link></div></div></header>
    <section className="page-width hero"><div><p className="eyebrow">Rooted in Ayurveda · Made for modern India</p><h1>One thoughtful addition to your daily ritual.</h1><p className="lede">{PRODUCT.description}</p><div className="actions"><Link className="pill" href="/product">Explore the product</Link><a className="pill-outline" href="https://amzn.in/d/05sFcLjk" target="_blank" rel="noreferrer">Buy on Amazon</a></div><div className="stat-row"><div className="stat"><strong>200g</strong><span>Net quantity</span></div><div className="stat"><strong>15+</strong><span>Ayurvedic herbs</span></div><div className="stat"><strong>₹1,499</strong><span>Offer price</span></div></div></div><div className="product-stage"><img className="product-image" src={PRODUCT.image} alt="ValuVeda Karela Jamun Powder product pack" /></div></section>
    <section id="story" className="section section-muted"><div className="page-width"><div className="section-head"><p className="eyebrow">The ValuVeda approach</p><h2>More clarity. Less noise.</h2><p className="lede">The product experience is designed around the information a customer needs to make a considered purchase—without unverified medical promises or invented credentials.</p></div><div className="card-grid">{facts.map(([number, title, body]) => <article className="card" key={number}><span className="eyebrow">{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section id="details" className="section section-dark"><div className="page-width split"><div><p className="eyebrow">Product details</p><h2>A premium 200g format with a simple story.</h2></div><div className="detail-list"><details open><summary>What is in the pack?</summary><p>The current product is ValuVeda Wellness Karela Jamun Powder, 200g, with Karela, Jamun and 15+ Ayurvedic herbs. Refer to the current pack label for the authoritative ingredient and usage details.</p></details><details><summary>How should it be used?</summary><p>Follow the serving and preparation directions printed on the current approved product label. If you take medication or have a medical condition, consult a qualified healthcare professional before adding a new herbal product.</p></details><details><summary>Where can I get help?</summary><p>Use the account and order support paths in this experience, or contact ValuVeda through the available assisted-order channel.</p></details></div></div></section>
    <section id="faq" className="section"><div className="page-width split"><div><p className="eyebrow">FAQ</p><h2>Before you order.</h2></div><div className="detail-list"><details><summary>What is the offer price?</summary><p>The current offer price shown for the 200g pack is ₹1,499 against an MRP of ₹2,499.</p></details><details><summary>Are these medical claims?</summary><p>No. ValuVeda presents this as a herbal wellness product. Product information does not promise to cure, reverse or guarantee control of any disease.</p></details><details><summary>Can I track an order?</summary><p>Yes. Authenticated customers can view their orders, while the order architecture keeps the ValuVeda order number, payment state and shipment state separate.</p></details></div></div></section>
    <section className="section section-muted"><div className="page-width" style={{display: "flex", justifyContent: "space-between", gap: 24, alignItems: "center", flexWrap: "wrap"}}><div><p className="eyebrow">Start here</p><h2 style={{marginBottom: 0}}>See the complete product story.</h2></div><Link className="pill" href="/product">View Karela Jamun Powder</Link></div></section>
    <footer className="footer"><div className="page-width footer-inner"><strong>ValuVeda Wellness</strong><span>Rooted in Ayurveda · Made for modern India</span></div></footer>
  </main>;
}
